### PR TITLE
ATF22 PLD breakout for motor controller and also Modular Battery

### PR DESCRIPTION
**Pull request by jackproudfoot**
Breakout board for ATF22 pld for mounting to teensy footprint.

### CODE REVIEW

**Comment by jackproudfoot** [comment]
Also added additional schematic for single battery module for the modular battery.

**Comment by jackproudfoot** [comment]
Datasheets for driver, dc/dc converter, and mosfets for reference

https://www.mouser.com/datasheet/2/792/r1200-ea-923668.pdf
https://www.infineon.com/dgdl/IPT004N03L_rev1.2.pdf?folderId=db3a304313b8b5a60113cee8763b02d7&fileId=db3a30433e9d5d11013e9e0f382600c2
https://www.silabs.com/documents/public/data-sheets/Si823x.pdf

**Comment by gchenfc** [comment]
edits to DC/DC and bootstrap

**Comment by gchenfc** [comment]
pretty good
1) on second thought, i don't think we need that resistor on the RC filter (U11) - I think just the capacitor is sufficient (not really sure why i thought we needed it in the first place)
2) the CE pin on the boost converter should be controllable through an isolator of some sort - we could also use a P/N MOSFET combo (See Figure 3 of https://www.onsemi.com/pub/Collateral/AND9093-D.PDF) which might be lower power
3) did you get the passive arrays footprints sorted out?
op amps look good

**Comment by gchenfc** [comment]
added supervisor IC for CE as well
https://www.digikey.com/product-detail/en/rohm-semiconductor/BD49K30G-TL/BD49K30G-TLCT-ND/3693404

**Comment by gchenfc** [comment]
added some pads for output port and beefed up some polygons
going to put the order in now

**Pull request merged**
